import sys
import traceback
import os

class CGenerator:
	def __init__(self, outputfile, summary, concrete_func, fakelib=None):

		self.fakelib =  f'{os.path.dirname(os.path.realpath(__file__))}/../Fake_libc/fake_libc_include'
		if fakelib is not None:
			self.fakelib = fakelib

		self.summary_path = summary
		self.concrete_file = concrete_func

		self.outputfile = outputfile
		self.tmp_files = []

	def _add_fake_include(self, file):
		fake_include = '#include <stdlib.h>\n'

		if not file:
			return None

		try:
			c = open(file, "r")
			c_lines = c.readlines()
			c.close()

			tmp_file = 'tmp_' + file.split('/')[-1]
		
			tmp_c = open(tmp_file, "w")
			tmp_c.writelines([fake_include] + c_lines)
			tmp_c.flush()
			tmp_c.close()

			self.tmp_files.append(tmp_file)
			return tmp_file

		except Exception:
			print(traceback.format_exc())
			self._exit(f'{file} not found')
	
	def _remove_files(self, *files):
		for f in files:
			if f and os.path.exists(f):
				os.remove(f)


	def _write_to_file(self, code, header, generator=None):

		header = [f'/*File generated by {generator}*/\n\n'] + header
		header.append('\n')
		header.append('\n')

		outfile = open(self.outputfile, "w")
		outfile.writelines(header)
		outfile.write(code)
		outfile.flush()
		outfile.close()

	def _exit(self, msg):
		try:
			self._remove_files(*self.tmp_files)
		except Exception:
				pass

		sys.exit(msg)